domains:
- domain: www.payonk.com
  type: PRIMARY
- domain: payonk.com
  type: ALIAS
name: payonk-jama
region: nyc
static_sites:
- build_command: script/build.sh
  environment_slug: gatsby
  envs:
  - key: NODE_ENV
    value: production
    scope: BUILD_TIME
  - key: COSMIC_BUCKET
    scope: BUILD_TIME
    value: payonk-jama
  - key: COSMIC_READ_KEY
    scope: BUILD_TIME
    type: SECRET
    value: EV[1:5JoN3ujouJKwGfR13zz8y6NA3nc4eeyg:f2PpjO4z0W1yUE3MIfipW4f90NlHOfXvtY6O3gf1MmNnbj8mATOndKY0JxnBHq/ZZ6Oq5NyTo5dniK7jkpdd7eko]
  - key: MAGIC_PUBLISHABLE_KEY
    scope: BUILD_TIME
    value: 'pk_test_05CC9C10E2A6DA8C'
  - key: BACKEND_ENDPOINT
    scope: BUILD_TIME
    value: https://api.payonk.com/graphql
  - key: HASURA_SECRET
    scope: BUILD_TIME
    type: SECRET
    value: EV[1:khxy0eA9x8Yc1r0LLRs0HDVb7NIsxq0Y:pUYGnDGQF7NG6v+zPcKk9x6icgrEZwudhaZm]
  github:
    branch: main
    deploy_on_push: true
    repo: dpayonk/payonk-jama
  name: payonk-jama
  routes:
  - path: /