domains:
- domain: www.payonk.com
  type: PRIMARY
- domain: payonk.com
  type: ALIAS
name: payonk-jama
region: nyc
static_sites:
- build_command: npm run build
  environment_slug: gatsby
  envs:
  - key: NODE_ENV
    value: production
    scope: BUILD_TIME
  - key: COSMIC_BUCKET
    scope: BUILD_TIME
    value: payonk-jama
  - key: COSMIC_READ_KEY
    scope: BUILD_TIME
    type: SECRET
    value: EV[1:WUPX1usWiNufHolgmJLuootnQNovpNEE:lwEX+wETAUbxokoyg6BU1RZa3IyO+BxzwTBrsCllMruUh18uBwnajmHtKYC7bykxPn6ihb+QbnHSsUwxK1qk7b0o]
  - key: MAGIC_PUBLISHABLE_KEY
    scope: BUILD_TIME
    value: 'pk_test_05CC9C10E2A6DA8C'
  - key: HASURA_ADMIN_TOKEN
    scope: BUILD_TIME
    type: SECRET
    value: EV[1:khxy0eA9x8Yc1r0LLRs0HDVb7NIsxq0Y:pUYGnDGQF7NG6v+zPcKk9x6icgrEZwudhaZm]
  github:
    branch: main
    deploy_on_push: true
    repo: dpayonk/payonk-jama
  name: payonk-jama
  routes:
  - path: /