import React, { Component } from "react"

class Loader extends Component {
  render() {
    return (
      <div className="loader-container">
      <div>
        <div className="loadingio-spinner-spinner-fgxiwf0l87e"><div className="ldio-z4leh78jxgi">
          <div /><div /><div /><div /><div /><div /><div /><div /><div /><div /><div /><div />
        </div></div>
        <style type="text/css" dangerouslySetInnerHTML={{ __html: "\n@keyframes ldio-z4leh78jxgi {\n  0% { opacity: 1 }\n  100% { opacity: 0 }\n}\n.ldio-z4leh78jxgi div {\n  left: 94px;\n  top: 48px;\n  position: absolute;\n  animation: ldio-z4leh78jxgi linear 1s infinite;\n  background: #1d3f72;\n  width: 12px;\n  height: 24px;\n  border-radius: 6px / 12px;\n  transform-origin: 6px 52px;\n}.ldio-z4leh78jxgi div:nth-child(1) {\n  transform: rotate(0deg);\n  animation-delay: -0.9166666666666666s;\n  background: #1d3f72;\n}.ldio-z4leh78jxgi div:nth-child(2) {\n  transform: rotate(30deg);\n  animation-delay: -0.8333333333333334s;\n  background: #1d3f72;\n}.ldio-z4leh78jxgi div:nth-child(3) {\n  transform: rotate(60deg);\n  animation-delay: -0.75s;\n  background: #1d3f72;\n}.ldio-z4leh78jxgi div:nth-child(4) {\n  transform: rotate(90deg);\n  animation-delay: -0.6666666666666666s;\n  background: #1d3f72;\n}.ldio-z4leh78jxgi div:nth-child(5) {\n  transform: rotate(120deg);\n  animation-delay: -0.5833333333333334s;\n  background: #1d3f72;\n}.ldio-z4leh78jxgi div:nth-child(6) {\n  transform: rotate(150deg);\n  animation-delay: -0.5s;\n  background: #1d3f72;\n}.ldio-z4leh78jxgi div:nth-child(7) {\n  transform: rotate(180deg);\n  animation-delay: -0.4166666666666667s;\n  background: #1d3f72;\n}.ldio-z4leh78jxgi div:nth-child(8) {\n  transform: rotate(210deg);\n  animation-delay: -0.3333333333333333s;\n  background: #1d3f72;\n}.ldio-z4leh78jxgi div:nth-child(9) {\n  transform: rotate(240deg);\n  animation-delay: -0.25s;\n  background: #1d3f72;\n}.ldio-z4leh78jxgi div:nth-child(10) {\n  transform: rotate(270deg);\n  animation-delay: -0.16666666666666666s;\n  background: #1d3f72;\n}.ldio-z4leh78jxgi div:nth-child(11) {\n  transform: rotate(300deg);\n  animation-delay: -0.08333333333333333s;\n  background: #1d3f72;\n}.ldio-z4leh78jxgi div:nth-child(12) {\n  transform: rotate(330deg);\n  animation-delay: 0s;\n  background: #1d3f72;\n}\n.loadingio-spinner-spinner-fgxiwf0l87e {\n  width: 200px;\n  height: 200px;\n  display: inline-block;\n  overflow: hidden;\n  background: none;\n}\n.ldio-z4leh78jxgi {\n  width: 100%;\n  height: 100%;\n  position: relative;\n  transform: translateZ(0) scale(1);\n  backface-visibility: hidden;\n  transform-origin: 0 0; /* see note above */\n}\n.ldio-z4leh78jxgi div { box-sizing: content-box; }\n/* generated by https://loading.io/ */\n" }} />
      </div>
      <label>{this.props.title}</label>
      </div>
    );
  }
}

export default Loader;